# From tutorial: https://github.com/timescale/private-rag-example

services:
  ollama:
    image: ollama/ollama
    networks:
      - default

  timescaledb:
    image: "timescale/timescaledb-ha:pg16"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - timescaledb:/home/postgres/pgdata/data
    networks:
      - default

  repl:  # TODO: Create a docker image running Python REPL with airag ready to use
    build:
      dockerfile: Dockerfile-repl
      context: .
    volumes:
      - ollama:/root/.ollama
    networks:
      - default

volumes:
  ollama:
  timescaledb:

networks:
  default:
