# From tutorial: https://github.com/timescale/private-rag-example

services:
  ollama:
    image: ollama/ollama
    networks:
      - default

  timescaledb:
    image: "timescale/timescaledb-ha:pg16"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - timescaledb:/home/postgres/pgdata/data
    networks:
      - default

  repl:
    build:
      dockerfile: Dockerfile-repl
      context: .
    volumes:
      - ollama:/root/.ollama
    networks:
      - default

  # puppeteer:  # FIXME: dev purpose
  #   build:
  #     dockerfile: sandbox/puppeteer-scraping/Dockerfile-puppeteer
  #     context: .

volumes:
  ollama:
  timescaledb:

networks:
  default:
